# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/
epicsEnvSet Vec1 192
epicsEnvSet Vec2 193
epicsEnvSet Vec3 194
epicsEnvSet Vec4 195
epicsEnvSet Vec5 196
epicsEnvSet Vec6 197
epicsEnvSet Vec7 198

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

asSetFilename /epics/support/pvlogging/src/access.acf
set_logging_enable 1
set_max_array_length 10
# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix BL19I-VA-IOC-01:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
# settings are restored at BOTH pass 0 (before iocInit) and pass 1
# (after iocInit), reproducing the legacy DLS level-1 semantics.
# Pass 0 is essential for records that self-initialise from their
# restored value at PINI - e.g. dlsPLC_temperature :HIGH, whose
# :HIGH_INIT calcout copies the restored :HIGH into the temperature
# record's .HIGH field during iocInit. With a pass-1-only restore
# that PINI runs before the value is restored and :HIGH collapses to
# 0. Pass 1 is also kept so PVs that get overwritten during init are
# restored on top afterwards.
set_pass0_restoreFile autosave_settings.sav
set_pass1_restoreFile autosave_settings.sav

# ipacAddHy8002("slot, intLevel")
ipacAddHy8002("4, 2")
# record above carrier card ID 0 in 'BL19I-VA-IOC-01.Slot4'
epicsEnvSet BL19I-VA-IOC-01.Slot4 0
ipacAddHy8002("5, 2")
# record above carrier card ID 1 in 'BL19I-VA-IOC-01.Slot5'
epicsEnvSet BL19I-VA-IOC-01.Slot5 1

#  Hy8001Configure(cardNum, vmeslotNum, vectorNum, itrLevel, debounce, clock, scan, direction, invertin, invertout)
Hy8001Configure(60, 6, $(Vec2), 0, 0, 0, 100, 0, 1, 1)
# Register the Hy8001 as an IPAC carrier so the card is mapped into VME
# address space - the VxWorks build did this with
# ipacEXTAddCarrier(&EXTHy8001, "<slot>"). Without it the Hy8001 bi/bo
# records (e.g. the VLVCC valve-crate interlocks on #C60) never
# reach the hardware. ipacAddHy8001 is the RTEMS wrapper (cf ipacAddHy8002).
ipacAddHy8001("6")

# DLS8515Configure(card id, carrier_index, interrupt_vector)
DLS8515Configure(40, $(BL19I-VA-IOC-01.Slot4), $(Vec3))
DLS8515Configure(41, $(BL19I-VA-IOC-01.Slot4), $(Vec4))

# DLS8516Configure(card_id, carrier_index, interrupt_vector)
DLS8516Configure(42, $(BL19I-VA-IOC-01.Slot4), $(Vec5))

# drvAsynSerialPortConfigure(name, port, priority, noAutoConnect, noProcessEos)
drvAsynSerialPortConfigure("ty_40_0", "/dev/tty400" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_1", "/dev/tty401" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_2", "/dev/tty402" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_3", "/dev/tty403" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_4", "/dev/tty404" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_5", "/dev/tty405" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_6", "/dev/tty406" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_7", "/dev/tty407" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_0", "/dev/tty410" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_1", "/dev/tty411" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_2", "/dev/tty412" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_3", "/dev/tty413" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_4", "/dev/tty414" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_5", "/dev/tty415" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_6", "/dev/tty416" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_7", "/dev/tty417" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_0", "/dev/tty420" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_1", "/dev/tty421" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_2", "/dev/tty422" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_3", "/dev/tty423" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_4", "/dev/tty424" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_5", "/dev/tty425" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_6", "/dev/tty426" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_7", "/dev/tty427" , 0, 0, 0)
# HostlinkInterposeInit(asyn_port)
HostlinkInterposeInit("ty_41_0")
# finsDEVInit(FINS_port_name, asyn_port)
finsDEVInit("ty_41_0.Hostlink", "ty_41_0")
# HostlinkInterposeInit(asyn_port)
HostlinkInterposeInit("ty_41_1")
# finsDEVInit(FINS_port_name, asyn_port)
finsDEVInit("ty_41_1.Hostlink", "ty_41_1")
# HostlinkInterposeInit(asyn_port)
HostlinkInterposeInit("ty_41_7")
# finsDEVInit(FINS_port_name, asyn_port)
finsDEVInit("ty_41_7.Hostlink", "ty_41_7")
# HostlinkInterposeInit(asyn_port)
HostlinkInterposeInit("ty_40_5")
# finsDEVInit(FINS_port_name, asyn_port)
finsDEVInit("ty_40_5.Hostlink", "ty_40_5")

# serial port settings from DL8515Channel
asynSetOption("ty_40_4",0,"parity","even")

asynSetOption("ty_40_5",0,"baud",57600)
asynSetOption("ty_40_5",0,"bits",7)
asynSetOption("ty_40_5",0,"parity","even")
asynSetOption("ty_40_5",0,"stop",2)

asynSetOption("ty_40_7",0,"baud",38400)

asynSetOption("ty_41_0",0,"baud",57600)
asynSetOption("ty_41_0",0,"bits",7)
asynSetOption("ty_41_0",0,"parity","even")
asynSetOption("ty_41_0",0,"stop",2)

asynSetOption("ty_41_1",0,"baud",57600)
asynSetOption("ty_41_1",0,"bits",7)
asynSetOption("ty_41_1",0,"parity","even")
asynSetOption("ty_41_1",0,"stop",2)

asynSetOption("ty_41_5",0,"parity","even")

asynSetOption("ty_41_6",0,"parity","even")

asynSetOption("ty_41_7",0,"baud",57600)
asynSetOption("ty_41_7",0,"bits",7)
asynSetOption("ty_41_7",0,"parity","even")
asynSetOption("ty_41_7",0,"stop",2)


# serial port settings from DL8516Channel

# Hy8401ipConfigure(cardNum, VMESlotNum, IPSlotNum, interruptVector, intEnable, aiType, externalClock, clockRate, inhibit, samples, spacing, triggered)
Hy8401ipConfigure(50, $(BL19I-VA-IOC-01.Slot5), 0, $(Vec6), 0, 0, 0, 15, 0, 1, 1, 0)
Hy8401ipConfigure(52, $(BL19I-VA-IOC-01.Slot5), 2, $(Vec7), 0, 0, 0, 15, 0, 1, 1, 0)

# ErConfigurePMC card_id card_index
ErConfigurePMC 1 0

dbLoadRecords /epics/runtime/ioc.db
iocInit

# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""
